INSERT INTO EMPLEADO (NOMBRE, APELLIDO, PASSWORD) VALUES ('Empleado', 'Prueba', '1234');
INSERT INTO CIUDADES (COD_POSTAL, NOMBRE) VALUES (18000, 'GRANADA');
INSERT INTO CLIENTE (NOMBRE, TELEFONO, DIRECCION, COD_POSTAL, PASSWORD, ID_EMPLEADO_ALTA) VALUES ('cliente', 123456789, 'calle etsiit', 18000, '1234',1);
INSERT INTO CLIENTE (NOMBRE, TELEFONO, DIRECCION, COD_POSTAL, PASSWORD, ID_EMPLEADO_ALTA) VALUES ('Cliente2',112345678, 'calle molotov', 18000, '12345',1);
INSERT INTO CLIENTE (NOMBRE, TELEFONO, DIRECCION, COD_POSTAL, PASSWORD, ID_EMPLEADO_ALTA) VALUES ('cliente3', 234567890, 'calle azor', 18000, '4321',1);
INSERT INTO CLIENTE (NOMBRE, TELEFONO, DIRECCION, COD_POSTAL, PASSWORD, ID_EMPLEADO_ALTA) VALUES ('Cliente4',132316789, 'calle rpg', 18000, '112345',1);


INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Camisetas L', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Camisetas M', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Camisetas XL', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Camisetas XXL', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Pantalones L', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Pantalones M', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Pantalones XL', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Pantalones XXL', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Jersey L', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Jersey M', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Jersey XL', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Jersey XXL', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Patatas L', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Patatas M', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Patatas XL', 10);
INSERT INTO STOCK (NOMBRE, CANTIDAD) VALUES ('Patatas XXL', 10);

INSERT INTO REPARTIDOR (NOMBRE, PASSWORD) VALUES ('repartidor', '1234');

--INSERT INTO PEDIDO (ID_CLIENTE,ID_PRODUCTO, ID_REPARTIDOR, FECHA_PEDIDO, FECHA_ENTREGA_PROGRAMADA, REPARTIDO, EN_REPARTO) VALUES (1,1,1,NOW(),NOW(),0,0);