--TRIGGER DE BAJA DE CLIENTE
-- AL DAR DE BAJA UN CLIENTE, DEBEMOS BORRAR LOS REGISTROS DE SUS COMPRAS REALIZADAS

DROP TRIGGER IF EXISTS BAJA_CLIENTE;
DELIMITER // -- DELIMITADOR PARA INTRODUCIR LAS SENTENCIAS DE TRIGGERS
CREATE TRIGGER BAJA_CLIENTE AFTER UPDATE ON CLIENTE 
FOR EACH ROW 
BEGIN
    IF (NEW.ID_EMPLEADO_BAJA IS NOT NULL) THEN
        DELETE FROM PEDIDO WHERE ID_CLIENTE = NEW.ID_CLIENTE;
        INSERT INTO BAJA_CLIENTE VALUES (NEW.ID_CLIENTE, NEW.ID_EMPLEADO_BAJA, NOW());
    END IF;
END; //


DROP TRIGGER IF EXISTS ALTA_CLIENTE;
CREATE TRIGGER ALTA_CLIENTE AFTER INSERT ON CLIENTE 
FOR EACH ROW 
BEGIN
    IF (NEW.ID_EMPLEADO_ALTA IS NOT NULL) THEN
        INSERT INTO ALTA_CLIENTE VALUES (NEW.ID_CLIENTE, NEW.ID_EMPLEADO_ALTA, NOW());
    END IF;
END; //

-- Existe pedido para cliente
-- Se realiza un PEDIDO y la Query es un INSERT, antes de hacer el insert en la tabla, se comprueba que efectivamente.
-- existe un producto.
DROP TRIGGER IF EXISTS EXISTE_PRODUCTO;
CREATE TRIGGER EXISTE_PRODUCTO BEFORE INSERT ON PEDIDO
FOR EACH ROW
BEGIN
    IF ((SELECT COUNT(*) FROM STOCK WHERE ID_PRODUCTO = NEW.ID_PRODUCTO) = 0) THEN
        SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO=30001, MESSAGE_TEXT='ERROR: No existe el producto seleccionado';
    END IF;
END; //

DROP TRIGGER IF EXISTS NO_STOCK;
CREATE TRIGGER NO_STOCK BEFORE UPDATE ON STOCK
FOR EACH ROW
BEGIN
    IF (NEW.CANTIDAD < 0) THEN
        SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO=30002, MESSAGE_TEXT='ERROR: Has introducido una cantidad que excede el stock';
    END IF;
END; //

DROP TRIGGER IF EXISTS FECHA_PROGRAMADA;
CREATE TRIGGER FECHA_PROGRAMADA BEFORE UPDATE ON PEDIDO
FOR EACH ROW
BEGIN
    IF ((SELECT FECHA_REPARTO FROM ESTADO_REPARTO WHERE ID_PEDIDO=NEW.ID_PEDIDO) < FECHA_ENTREGA_PROGRAMADA) THEN
        UPDATE ESTADO_REPARTO SET FECHA_REPARTO=FECHA_ENTREGA_PROGRAMADA WHERE ID_PEDIDO=NEW.ID_PEDIDO;
    END IF;
END; //

DROP TRIGGER IF EXISTS SELECT_PEDIDO_CORRECTO;
CREATE TRIGGER SELECT_PEDIDO_CORRECTO BEFORE UPDATE ON PEDIDO
FOR EACH ROW
BEGIN
    IF ((SELECT COUNT(*) FROM PEDIDO WHERE ID_PEDIDO=NEW.ID_PEDIDO AND EN_REPARTO = 1 ) = 0) THEN
        SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO=30003, MESSAGE_TEXT='ERROR: El pedido ha sido solicitado por otro repartidor';
    END IF;
END; // 

DROP TRIGGER IF EXISTS 
        


DELIMITER ;